### ISSUE TITLE
Support for armv7l?

### ISSUE THREAD

**Issue by robbiet480** [robotastic/docker-gnuradio#2]
Any chance support for armv7l can be added? Would provide a faster way to get going on Raspberry Pi.

**Comment by robotastic** [comment]
Definitely! Any good pointers on how to have DockerHub automatically build for those platforms? Do I need to cross-compile on my Mac.

**Comment by robbiet480** [comment]
I looked into this a bit today and seems the easiest way to go about this would be to use [docker buildx](https://docs.docker.com/buildx/working-with-buildx/). Gonna do some tests locally and see how hard it is to get this and then trunk-recorder building.

**Comment by robbiet480** [comment]
This was easier than I thought it would be! Took less than 30 minutes to have complete builds uploaded to Docker Hub. Here's all the commands I had to run locally on my Mac to get builds going:

1. Enable experimental mode on Docker Desktop for Mac: Docker menu bar item > Preferences > Command Line and then turn on the Enable experimental features toggle. Click Apply & Restart.
2. `docker buildx create --name testbuilder`
3. `docker buildx use testbuilder`
4. `docker buildx inspect --bootstrap` (the bootstrap is the key, it'll create the VMs used for builds)
5. `docker login` if you aren't already
6. `docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t robotastic/docker-gnuradio --push .`
7. The build took 791.4s and get automatically uploaded to Docker Hub. You can view mine [here](https://hub.docker.com/r/robbiet480/docker-gnuradio).

Figured it out thanks to [docker buildx docs](https://docs.docker.com/buildx/working-with-buildx/) and [this article](https://collabnix.com/building-arm-based-docker-images-on-docker-desktop-made-possible-using-buildx/) that shows exactly how to build for rPi.

**Comment by robbiet480** [comment]
As for `trunk-recorder`, it took a **lot** longer to build: 75 minutes! Weirdly, building `armv7` took almost 20 minutes _less_ than building for `arm64` (`amd64` only took 200 seconds). I don't think its the limits of my machine either, i'm on a brand new fully loaded 16" MacBook Pro. It's extremely likely there's cross compile flags that could be set to speed up the time. Thankfully, I didn't have to make changes there either, just ran `docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t robotastic/trunk-recorder --push .`. I'd suggest running that as part of a Travis or other CI run since Docker Hub builds don't yet support `buildx`. More info on that at https://github.com/docker/hub-feedback/issues/1874

You can view mine [here](https://hub.docker.com/r/robbiet480/trunk-recorder).

**Comment by robbiet480** [comment]
Continuing this at https://github.com/robotastic/trunk-recorder/issues/365
